{
 "title": "Pool Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "ESSENTIAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UP TIME",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    { "expr": "rts_gc_wall_ms / (1000)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "KES ROTATION",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(cardano_node_metrics_remainingKESPeriods_int * 1.5)",
     "legendFormat": "Days left"
    },
    {
     "expr": "cardano_node_metrics_currentKESPeriod_int",
     "legendFormat": "Current period"
    },
    {
     "expr": "cardano_node_metrics_operationalCertificateExpiryKESPeriod_int",
     "legendFormat": "Expiry period"
    }
   ]
  },
  {
   "title": "TIME SYNC OFFSET",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_timex_maxerror_seconds", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "TRANSACTIONS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "PEERS OUT",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectedPeers_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SLOT IN EPOCH",
   "type": "gauge",
   "description": "● Green means slot leader schedule for the next epoch is available. <BR>\n● This is slot number of the last block.",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int{instance=\"localhost:12798\"}"
    }
   ]
  },
  {
   "title": "BLOCK",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int{instance=\"localhost:12798\"}"
    }
   ]
  },
  {
   "title": "EPOCH",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_epoch_int{instance=\"localhost:12798\"}"
    }
   ]
  },
  {
   "title": "SLOT",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int{instance=\"localhost:12798\"}"
    }
   ]
  },
  {
   "title": "CHAIN DENSITY",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_density_real{instance=\"localhost:12798\"} * 100"
    }
   ]
  },
  { "title": "CRITICAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "MISSED SLOTS",
   "type": "graph",
   "description": "Missed slots are slots that your block-producing node cannot check if it is a leader or not. If you are sheduled to lead those slots, you will lose your block.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_slotsMissedNum_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SLOTS LED",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_node_is_leader_int"
    }
   ]
  },
  {
   "title": "BLOCKS FORGED",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_int"
    }
   ]
  },
  {
   "title": "BLOCKS REJECTED",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_int - cardano_node_metrics_Forge_adopted_int"
    }
   ]
  },
  { "title": "SYSTEM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MEMORY USED",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{alias!~\"monitoring.*\"} - node_memory_MemFree_bytes{alias!~\"monitoring.*\"}) / node_memory_MemTotal_bytes{alias!~\"monitoring.*\"} * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NETWORK",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[1m])*8",
     "legendFormat": "RECEIVE (+) {{instance}}"
    },
    {
     "expr": "-irate(node_network_transmit_bytes_total[1m])*8",
     "legendFormat": "TRANSMIT (-) {{instance}}"
    }
   ]
  },
  {
   "title": "DISK SPACE USED",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "OTHERS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "RESIDENCY (Amount of live data)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used/(1024*1024)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MEMPOOL TRANSACTIONS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MEMPOOL BYTES",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_mempoolBytes_int",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DISK IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total[1m])",
     "legendFormat": "READ (+) {{instance}}"
    },
    {
     "expr": "-irate(node_disk_written_bytes_total[1m])",
     "legendFormat": "WRITE (-) {{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 31 },
   "options": {
    "content": "<div style=\"font-weight: 400; margin: 0 auto; max-width: 600px; font-size: 20px; word-wrap: break-word;\">\n<BR>\n\nThis dashboard is brought to you by STAY pool. \n<br>\nAny support is greatly appreciated 🙏\n<br>\n<BR>● Delegate to my pool, ticker: <b><i>STAY</i></b>\n<BR>● Donate to my address: <i>addr1qyxd2rpa3fwxpj739zcddwac5knke4s2casn0czfr32v5zf6g5qmpfv40fal70xtuqc4wx4h708h26l78eajgmhuvntqhkhr4z</i>\n<BR><BR>\n<center>\n<img src=\"https://lh3.googleusercontent.com/CpK57oc4wzCgvi_HbxnTPKEf1KSj7fVTEUnuGuGeesusjFeJtNW7LEkjNnFCxD8b-lMJ3E3L0u8Mz6MXZQo8AEcFa_bcE347NNYW\" width=150 height=150>\n</center>\n</div>"
   }
  }
 ]
}